spring:
  application:
    name: ssok-openbanking

  kafka:
    bootstrap-servers: localhost:9092
    request-topic: request-topic
    reply-topic: reply-topic
    push-topic: push-topic
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: kr.ssok.model
      auto-offset-reset: earliest

  data:
    redis:
      host: kudong.kr
      port: 55032

  datasource:
    username: lgcns
    password: password
    url: jdbc:mariadb://kudong.kr:55023/moni?useUnicode=true&characterEncoding=utf-8&serverTimeZone=Asia/Seoul
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
        use_sql_comments: 'true'
        format_sql: 'true'
        show_sql: 'true'
    hibernate:
      ddl-auto: update

  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 10000
            readTimeout: 10000
            loggerLevel: full

logging:
  level:
    kr.ssok.ssokopenbanking: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.web.client.RestTemplate: DEBUG
    kr.ssok.ssokopenbanking.transfer.client: DEBUG

bank:
  api:
    url: http://kudong.kr:55027
  global:
    api:
      url: https://dev-global-bank-api.example.com

server:
  port: 8080
